// src/data/products.ts (Updated with ALL products)

export const allProducts = [
    // --- OTT Accounts (ID Range: 100s) ---
    { id: 101, name: 'Netflix Premium UHD', price: 149, originalPrice: 649, description: 'Premium Netflix account with 4K streaming and multi-device support for the ultimate entertainment experience.', features: [{ title: '4K Ultra HD', desc: 'Stream in stunning 4K quality with HDR support' }, { title: '4 Screens', desc: 'Watch on up to 4 devices simultaneously' }, { title: 'Download Feature', desc: 'Download content for offline viewing' }, { title: '6 Month Validity', desc: 'Full access for 6 months with warranty' }], tags: ['Streaming', '4K', 'Netflix'], category: 'OTT', image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=60', gradient: 'from-red-500 to-black', buttonColor: 'from-red-500 to-red-700' },
    { id: 102, name: 'Spotify Premium Family', price: 99, originalPrice: 329, description: 'Spotify Premium Family account for up to 6 users with offline downloads and ad-free experience.', features: [{ title: '6 Users Access', desc: 'Share with up to 6 family members' }, { title: 'Ad-Free Music', desc: 'Enjoy uninterrupted music streaming' }], tags: ['Music', 'Family', 'Spotify'], category: 'OTT', image: 'https://images.unsplash.com/photo-1619983081563-430f545b4e7b?auto=format&fit=crop&w=800&q=60', gradient: 'from-green-500 to-black', buttonColor: 'from-green-500 to-green-700' },
    { id: 103, name: 'Disney+ Hotstar Premium', price: 199, originalPrice: 399, description: 'Premium Disney+ Hotstar with live sports and exclusive content for entertainment lovers.', features: [{ title: 'Live Sports', desc: 'Watch live cricket, football and other sports' }, { title: 'Latest Movies', desc: 'Access to newest movie releases' }], tags: ['Streaming', 'Sports', 'Disney'], category: 'OTT', image: 'https://images.unsplash.com/photo-1627914830172-83b63bf0547b?auto=format&fit=crop&w=800&q=60', gradient: 'from-orange-500 to-black', buttonColor: 'from-orange-500 to-orange-700' },
    
    // --- Product Keys (ID Range: 200s) ---
    { id: 201, name: 'Windows 11 Pro Key', price: 299, originalPrice: 1999, description: 'Genuine Windows 11 Pro license key with lifetime validity.', features: [{ title: 'Lifetime License', desc: 'Permanent activation' }, { title: 'Digital Delivery', desc: 'Instant email delivery' }], tags: ['OS', 'Microsoft', 'Windows'], category: 'Keys', image: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?auto=format&fit=crop&w=800&q=60', gradient: 'from-blue-500 to-black', buttonColor: 'from-blue-500 to-blue-700' },
    { id: 202, name: 'Microsoft Office 2021 Key', price: 399, originalPrice: 2499, description: 'Complete Microsoft Office 2021 suite for productivity.', features: [{ title: 'Word, Excel, etc.', desc: 'Complete office suite' }, { title: 'Lifetime License', desc: 'One-time purchase' }], tags: ['Office', 'Productivity', 'Microsoft'], category: 'Keys', image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=800&q=60', gradient: 'from-orange-500 to-black', buttonColor: 'from-orange-500 to-orange-700' },
    { id: 203, name: 'Adobe Creative Cloud', price: 599, originalPrice: 3999, description: 'Complete Adobe Creative Cloud subscription with all professional design tools.', features: [{ title: 'All Adobe Apps', desc: 'Photoshop, Illustrator, etc.' }, { title: '1 Year License', desc: 'Full year subscription' }], tags: ['Creative', 'Design'], category: 'Keys', image: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=800&q=60', gradient: 'from-red-500 to-black', buttonColor: 'from-red-500 to-red-700' },

    // --- IPTV Subscriptions (ID Range: 300s) ---
    { id: 301, name: 'Basic HD IPTV Pack', price: 299, originalPrice: 599, description: 'Over 500+ channels in high definition for family entertainment.', features: [{ title: '500+ Channels', desc: 'All popular local channels' }, { title: '720p HD', desc: 'Good streaming quality' }], tags: ['HD', 'Basic', 'IPTV'], category: 'IPTV', image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=800&q=60', gradient: 'from-purple-500 to-black', buttonColor: 'from-purple-500 to-purple-700' },
    { id: 302, name: 'Premium 4K UHD IPTV', price: 599, originalPrice: 1299, description: 'Experience the best quality with 4K channels and a massive VOD library.', features: [{ title: '2000+ Channels', desc: 'Worldwide channels' }, { title: '4K UHD', desc: 'Crystal clear picture' }], tags: ['4K', 'Premium', 'IPTV'], category: 'IPTV', image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?auto=format&fit=crop&w=800&q=60', gradient: 'from-indigo-500 to-black', buttonColor: 'from-indigo-500 to-indigo-700' },

    // --- Downloads (ID Range: 400s) ---
    { id: 401, name: 'AAA Games Collection', price: 499, originalPrice: 2999, description: 'A massive collection of the latest AAA games including all DLCs.', features: [{ title: '50+ AAA Games', desc: 'All major titles' }, { title: 'Includes DLCs', desc: 'Expansions and extras' }], tags: ['Games', 'AAA', 'PC'], category: 'Downloads', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=60', gradient: 'from-rose-500 to-black', buttonColor: 'from-rose-500 to-rose-700' },
    { id: 402, name: 'Pro Software Suite', price: 399, originalPrice: 1999, description: 'A bundle of professional software for video editing, design, and productivity.', features: [{ title: '10+ Pro Apps', desc: 'For professionals' }, { title: 'Lifetime Updates', desc: 'Free future updates' }], tags: ['Software', 'Bundle', 'PC'], category: 'Downloads', image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=800&q=60', gradient: 'from-amber-500 to-black', buttonColor: 'from-amber-500 to-amber-700' }
];